### PR TITLE
fix!: remove invalid feedback types and add missing ones

### PR DESCRIPTION
**Pull request by figueredo**
Removes no longer valid feedback types (or custom types) and adds missing ones.

This is a breaking change.

### CODE REVIEW

**Review by ottony — CHANGES_REQUESTED** [review]
As it's a breaking change we need to bump the version to 1.1.0

https://github.com/inloco/incognia-ruby/blob/main/README.md#development
> To release a new version, update the version number in version.rb, run bundle to update the gemfile.lock, add one description on CHANGELOG.md if necessary, and then after merging on master, run bundle exec rake release.

**Comment by figueredo** [comment]
Thanks, I'll change the version. Wouldn't it be 2.0.0 (are we using semantic versioning?)?

**Comment by ottony** [comment]
> Thanks, I'll change the version. Wouldn't it be 2.0.0 (are we using semantic versioning?)?

Yes, we are. You're right :+1:

**Comment by figueredo** [comment]
Changed version on #27, which should be released together with this. Also added a version bump to #25.

**Pull request merged**
